### ISSUE TITLE
[Feature Request] Upload file from commandline

### ISSUE THREAD

**Issue by silverwolfceh** [hoangvu12/file-up#1]
Hello @hoangvu12,

Would you please consider adding command line upload?

I used to use transfer .sh but now it is really heavy and unaccessable.

Thanks.

**Comment by hoangvu12** [comment]
You can simply upload to FileDitch using a CURL command.
```sh
curl -i -F files[]=@yourfile.jpeg https://up1.fileditch.com/upload.php
```
